/** @format */

export const DATA = [
  {
    id: 0,
    title: "Iphone-x",
    price: 750,
    Desc: "The iPhone is Apple's iconic mobile device, combining a powerful processor, an intuitive interface, and an expansive app store. The iPhone features a touchscreen display, allowing users to interact with the device using finger gestures. It also features a powerful camera, allowing users to take beautiful photos and videos. Additionally, the device comes with a variety of apps, such as the App Store, iTunes, and Maps, and it is capable of connecting to high-speed cellular networks, allowing users to stay connected while on the go.",
    img: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-x-new-1.jpg",
  },
  {
    id: 1,
    title: "Iphone-xs",
    price: 850,
    Desc: "The iPhone is Apple's iconic mobile device, combining a powerful processor, an intuitive interface, and an expansive app store. The iPhone features a touchscreen display, allowing users to interact with the device using finger gestures. It also features a powerful camera, allowing users to take beautiful photos and videos. Additionally, the device comes with a variety of apps, such as the App Store, iTunes, and Maps, and it is capable of connecting to high-speed cellular networks, allowing users to stay connected while on the go.",
    img: "https://www.cnet.com/a/img/resize/1315c1e033c31b8ad3fc61d1819e45930669b0c4/hub/2018/09/17/ff8ce8b7-fb73-4d2b-ae99-f546652e38df/44-iphone-xs.jpg?auto=webp&width=1200",
  },
  {
    id: 2,
    title: "Iphone-xs-max",
    price: 950,
    Desc: "The iPhone is Apple's iconic mobile device, combining a powerful processor, an intuitive interface, and an expansive app store. The iPhone features a touchscreen display, allowing users to interact with the device using finger gestures. It also features a powerful camera, allowing users to take beautiful photos and videos. Additionally, the device comes with a variety of apps, such as the App Store, iTunes, and Maps, and it is capable of connecting to high-speed cellular networks, allowing users to stay connected while on the go.",
    img: "https://images.unsplash.com/photo-1622957041673-7538e268a01d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80",
  },
  {
    id: 3,
    title: "Iphone-11",
    price: 1050,
    Desc: "The iPhone is Apple's iconic mobile device, combining a powerful processor, an intuitive interface, and an expansive app store. The iPhone features a touchscreen display, allowing users to interact with the device using finger gestures. It also features a powerful camera, allowing users to take beautiful photos and videos. Additionally, the device comes with a variety of apps, such as the App Store, iTunes, and Maps, and it is capable of connecting to high-speed cellular networks, allowing users to stay connected while on the go.",
    img: "https://images.unsplash.com/photo-1635173758550-ba42cd01e289?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjF8fGlwaG9uZSUyMDExfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 4,
    title: "Iphone-11-pro",
    price: 1150,
    Desc: "The iPhone is Apple's iconic mobile device, combining a powerful processor, an intuitive interface, and an expansive app store. The iPhone features a touchscreen display, allowing users to interact with the device using finger gestures. It also features a powerful camera, allowing users to take beautiful photos and videos. Additionally, the device comes with a variety of apps, such as the App Store, iTunes, and Maps, and it is capable of connecting to high-speed cellular networks, allowing users to stay connected while on the go.",
    img: "https://images.unsplash.com/photo-1603898037225-1bea09c550c0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8aXBob25lJTIwMTElMjBwcm98ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 5,
    title: "Iphone-11-pro_Max",
    price: 1350,
    Desc: "The iPhone is Apple's iconic mobile device, combining a powerful processor, an intuitive interface, and an expansive app store. The iPhone features a touchscreen display, allowing users to interact with the device using finger gestures. It also features a powerful camera, allowing users to take beautiful photos and videos. Additionally, the device comes with a variety of apps, such as the App Store, iTunes, and Maps, and it is capable of connecting to high-speed cellular networks, allowing users to stay connected while on the go.",
    img: "https://images.unsplash.com/photo-1581795669633-91ef7c9699a8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8aXBob25lJTIwMTElMjBwcm8lMjBtYXh8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 6,
    title: "Iphone-12",
    price: 1450,
    Desc: "The iPhone is Apple's iconic mobile device, combining a powerful processor, an intuitive interface, and an expansive app store. The iPhone features a touchscreen display, allowing users to interact with the device using finger gestures. It also features a powerful camera, allowing users to take beautiful photos and videos. Additionally, the device comes with a variety of apps, such as the App Store, iTunes, and Maps, and it is capable of connecting to high-speed cellular networks, allowing users to stay connected while on the go.",
    img: "https://images.unsplash.com/photo-1621939703744-9b75e3f7ff0e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8aXBob25lJTIwMTJ8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 7,
    title: "Iphone-12-pro_Max",
    price: 1450,
    Desc: "The iPhone is Apple's iconic mobile device, combining a powerful processor, an intuitive interface, and an expansive app store. The iPhone features a touchscreen display, allowing users to interact with the device using finger gestures. It also features a powerful camera, allowing users to take beautiful photos and videos. Additionally, the device comes with a variety of apps, such as the App Store, iTunes, and Maps, and it is capable of connecting to high-speed cellular networks, allowing users to stay connected while on the go.",
    img: "https://images.unsplash.com/photo-1611791485440-24e8239a0377?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGlwaG9uZSUyMDEyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 8,
    title: "Iphone-13",
    price: 1650,
    Desc: "The iPhone is Apple's iconic mobile device, combining a powerful processor, an intuitive interface, and an expansive app store. The iPhone features a touchscreen display, allowing users to interact with the device using finger gestures. It also features a powerful camera, allowing users to take beautiful photos and videos. Additionally, the device comes with a variety of apps, such as the App Store, iTunes, and Maps, and it is capable of connecting to high-speed cellular networks, allowing users to stay connected while on the go.",
    img: "https://images.unsplash.com/photo-1635425730507-26c324aadbc5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fGlwaG9uZSUyMDEzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 9,
    title: "Iphone 13-pro_Max",
    price: 1750,
    Desc: "The iPhone is Apple's iconic mobile device, combining a powerful processor, an intuitive interface, and an expansive app store. The iPhone features a touchscreen display, allowing users to interact with the device using finger gestures. It also features a powerful camera, allowing users to take beautiful photos and videos. Additionally, the device comes with a variety of apps, such as the App Store, iTunes, and Maps, and it is capable of connecting to high-speed cellular networks, allowing users to stay connected while on the go.",
    img: "https://images.unsplash.com/photo-1632661674596-df8be070a5c5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8aXBob25lJTIwMTMlMjBwcm8lMjBtYXh8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 10,
    title: "Iphone-13 Colors",
    price: 1750,
    Desc: "The iPhone is Apple's iconic mobile device, combining a powerful processor, an intuitive interface, and an expansive app store. The iPhone features a touchscreen display, allowing users to interact with the device using finger gestures. It also features a powerful camera, allowing users to take beautiful photos and videos. Additionally, the device comes with a variety of apps, such as the App Store, iTunes, and Maps, and it is capable of connecting to high-speed cellular networks, allowing users to stay connected while on the go.",
    img: "https://i.dailymail.co.uk/1s/2021/09/10/18/47759687-9978095-image-a-4_1631294477745.jpg",
  },
  {
    id: 11,
    title: "Iphone-14",
    price: 2000,
    Desc: "The iPhone is Apple's iconic mobile device, combining a powerful processor, an intuitive interface, and an expansive app store. The iPhone features a touchscreen display, allowing users to interact with the device using finger gestures. It also features a powerful camera, allowing users to take beautiful photos and videos. Additionally, the device comes with a variety of apps, such as the App Store, iTunes, and Maps, and it is capable of connecting to high-speed cellular networks, allowing users to stay connected while on the go.",
    img: "https://images.unsplash.com/photo-1663408261842-016bae520a0c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzF8fGlwaG9uZSUyMDE0JTIwcHJvfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 12,
    title: "Iphone-14 Pro",
    price: 2000,
    Desc: "The iPhone is Apple's iconic mobile device, combining a powerful processor, an intuitive interface, and an expansive app store. The iPhone features a touchscreen display, allowing users to interact with the device using finger gestures. It also features a powerful camera, allowing users to take beautiful photos and videos. Additionally, the device comes with a variety of apps, such as the App Store, iTunes, and Maps, and it is capable of connecting to high-speed cellular networks, allowing users to stay connected while on the go.",
    img: "https://images.unsplash.com/photo-1671899736981-d917010b8fb4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8aXBob25lJTIwMTQlMjBwcm8lMjBtYXglMjB3YWxscGFwZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 13,
    title: "Iphone-14 Pro",
    price: 2000,
    Desc: "The iPhone is Apple's iconic mobile device, combining a powerful processor, an intuitive interface, and an expansive app store. The iPhone features a touchscreen display, allowing users to interact with the device using finger gestures. It also features a powerful camera, allowing users to take beautiful photos and videos. Additionally, the device comes with a variety of apps, such as the App Store, iTunes, and Maps, and it is capable of connecting to high-speed cellular networks, allowing users to stay connected while on the go.",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXcAKLIVMmHPjIp__ZtvUEHfQ4KSVFpqwH7Q&usqp=CAU",
  },
  {
    id: 14,
    title: "Iphone-14 Pro",
    price: 2000,
    Desc: "The iPhone is Apple's iconic mobile device, combining a powerful processor, an intuitive interface, and an expansive app store. The iPhone features a touchscreen display, allowing users to interact with the device using finger gestures. It also features a powerful camera, allowing users to take beautiful photos and videos. Additionally, the device comes with a variety of apps, such as the App Store, iTunes, and Maps, and it is capable of connecting to high-speed cellular networks, allowing users to stay connected while on the go.",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4m2KsQa4FdP-aqK4-wKLPP3RT5Tr28T7Ekg&usqp=CAU",
  },
];
